run:
  allow-parallel-runners: true

output:
  sort-results: true

linters-settings:
  tagliatelle:
    case:
      # use the struct field name to check the name of the struct tag
      use-field-name: false
      rules:
        json: camel
        yaml: camel
        envconfig: lower
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - prefix(github.com) # Custom section: groups all imports with the specified Prefix.
      - default # Default section: contains all imports that could not be matched to another section type.
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    custom-order: true
  gocyclo:
    min-complexity: 15


linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    # unused
    - ineffassign
    - unused
    #complexity
    - nestif
    - gocyclo
    # import
    - gci
    # bugs
    - bodyclose
    - errcheck
    - govet
    - staticcheck
    - typecheck
    # comment
    - godot
    # format
    - gofumpt
    #style
    - gosimple
    - dogsled
    - errname
    - goconst
    - gomnd
    - tagliatelle
    - unconvert

